Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Lint/UselessAssignment:
  Enabled: true
  AutoCorrect: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Lint/UnusedMethodArgument:
  AutoCorrect: false
Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/LineLength:
  Max: 100
