Layout:
  Enabled: false

Layout/LineLength:
  Enabled: true

Style/MultilineIfModifier:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/QuotedSymbols:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Lint/UselessAssignment:
  Enabled: true
  AutoCorrect: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Lint/UnusedMethodArgument:
  AutoCorrect: false

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineLength:
  Max: 100
